config/routes.rb
Rails.application.routes.draw do
  get 'quotes/index'
  resources :quotes
  root 'quotes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  include QuotesHelper
  def index
    @quotes = Quote.all
  end
  def new

  end
  def create
    @quote = Quote.new(quote_params)
    @quote.save
    redirect_to quotes_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def quote_params
    params.require(:quote).permit(:citation)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/index.html.erb
<h1>Anonymous Quotes</h1>

<table>
  <% @quotes.each do |quote| %>
    <tr>
      <td><i>"<%= quote.citation %>"</i></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Add new quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>Add new quote</h1>
<%= form_with scope: :quote, url: quotes_path, local: true do |form| %>
  <p>
    <%= form.label :new_quote %><br>
    <%= form.text_area :citation %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>